version: '3.1'

services:

  api:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app

  postgres:
    image: postgres
    environment:
      POSTGRES_PASSWORD: password

  adminer:
    image: adminer
    ports:
      - "8080:8080"