version: '3.1'

services:

  api:
    build: .
    ports:
      - "8000:8000"
    environment:
      SECRETS_FILENAME: /run/secrets/secrets_file
      TEST_MONGO_URI: mongodb://root:example@mongo:27017/
    container_name: "tfg-aletheia-api"
    volumes:
      - .:/app
    secrets:
      - secrets_file

  postgres:
    image: postgres
    environment:
      POSTGRES_PASSWORD: password

  mongo:
    image: mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  mongo-express:
    image: mongo-express
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/
      ME_CONFIG_BASICAUTH: "false"

  adminer:
    image: adminer
    ports:
      - "8080:8080"

secrets:
  secrets_file:
    file: "secrets.json"