version: '3.1'

services:

  api:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      SECRETS_FILENAME: /run/secrets/secrets_file
    secrets:
      - secrets_file

  postgres:
    image: postgres
    environment:
      POSTGRES_PASSWORD: password

  adminer:
    image: adminer
    ports:
      - "8080:8080"

secrets:
  secrets_file:
    file: "secrets.json"