from enum import StrEnum


class TeacherPosition(StrEnum):
    ASSISTANT = "ASSISTANT"
    POSTDOC_RESEARCHER = "POSTDOC_RESEARCHER"
    ASSOCIATED_PROFESSOR = "ASSOCIATED_PROFESSOR"
    SENIOR_LECTURER = "SENIOR_LECTURER"
    FULL_PROFESSOR = "FULL_PROFESSOR"
    ADJUNCT_PROFESSOR = "ADJUNCT_PROFESSOR"
    VISITING_PROFESSOR = "VISITING_PROFESSOR"
    PROFESSOR_EMERITUS = "PROFESSOR_EMERITUS"
