name: Run tests

on:
  pull_request:
    branches: [ "develop" ]
    types:
      - closed

permissions:
  contents: read

jobs:
  build:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: password
          POSTGRES_DB: postgres
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5    

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.11"
    - name: Install Poetry
      run: |
          pip install poetry
          poetry self update
    - name: Install dependencies
      run: poetry install
    - name: Run all tests
      run: |
        poetry run pytest test
      env:
        SECRETS_ENVFILE: ./secrets.json
        DEBUG: 0
        DATABASE_ECHO: 0